name = "grd-foundation-core"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_VERSION = "2"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
