/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWebmailRouteImport } from './routes/app.webmail'
import { Route as AppPontoRouteImport } from './routes/app.ponto'
import { Route as AppComercialRouteImport } from './routes/app.comercial'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppProjetosIndexRouteImport } from './routes/app.projetos.index'
import { Route as AppEquipamentosIndexRouteImport } from './routes/app.equipamentos.index'
import { Route as AppProjetosIdRouteImport } from './routes/app.projetos.$id'
import { Route as AppEquipamentosIdRouteImport } from './routes/app.equipamentos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebmailRoute = AppWebmailRouteImport.update({
  id: '/webmail',
  path: '/webmail',
  getParentRoute: () => AppRoute,
} as any)
const AppPontoRoute = AppPontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => AppRoute,
} as any)
const AppComercialRoute = AppComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosIndexRoute = AppProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosIndexRoute = AppEquipamentosIndexRouteImport.update({
  id: '/equipamentos/',
  path: '/equipamentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosIdRoute = AppProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosIdRoute = AppEquipamentosIdRouteImport.update({
  id: '/equipamentos/$id',
  path: '/equipamentos/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/ponto': typeof AppPontoRoute
  '/app/webmail': typeof AppWebmailRoute
  '/app/': typeof AppIndexRoute
  '/app/equipamentos/$id': typeof AppEquipamentosIdRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
  '/app/equipamentos/': typeof AppEquipamentosIndexRoute
  '/app/projetos/': typeof AppProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/ponto': typeof AppPontoRoute
  '/app/webmail': typeof AppWebmailRoute
  '/app': typeof AppIndexRoute
  '/app/equipamentos/$id': typeof AppEquipamentosIdRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
  '/app/equipamentos': typeof AppEquipamentosIndexRoute
  '/app/projetos': typeof AppProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/ponto': typeof AppPontoRoute
  '/app/webmail': typeof AppWebmailRoute
  '/app/': typeof AppIndexRoute
  '/app/equipamentos/$id': typeof AppEquipamentosIdRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
  '/app/equipamentos/': typeof AppEquipamentosIndexRoute
  '/app/projetos/': typeof AppProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/comercial'
    | '/app/ponto'
    | '/app/webmail'
    | '/app/'
    | '/app/equipamentos/$id'
    | '/app/projetos/$id'
    | '/app/equipamentos/'
    | '/app/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/admin'
    | '/app/comercial'
    | '/app/ponto'
    | '/app/webmail'
    | '/app'
    | '/app/equipamentos/$id'
    | '/app/projetos/$id'
    | '/app/equipamentos'
    | '/app/projetos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/comercial'
    | '/app/ponto'
    | '/app/webmail'
    | '/app/'
    | '/app/equipamentos/$id'
    | '/app/projetos/$id'
    | '/app/equipamentos/'
    | '/app/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webmail': {
      id: '/app/webmail'
      path: '/webmail'
      fullPath: '/app/webmail'
      preLoaderRoute: typeof AppWebmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ponto': {
      id: '/app/ponto'
      path: '/ponto'
      fullPath: '/app/ponto'
      preLoaderRoute: typeof AppPontoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comercial': {
      id: '/app/comercial'
      path: '/comercial'
      fullPath: '/app/comercial'
      preLoaderRoute: typeof AppComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos/': {
      id: '/app/projetos/'
      path: '/projetos'
      fullPath: '/app/projetos/'
      preLoaderRoute: typeof AppProjetosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipamentos/': {
      id: '/app/equipamentos/'
      path: '/equipamentos'
      fullPath: '/app/equipamentos/'
      preLoaderRoute: typeof AppEquipamentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos/$id': {
      id: '/app/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/app/projetos/$id'
      preLoaderRoute: typeof AppProjetosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipamentos/$id': {
      id: '/app/equipamentos/$id'
      path: '/equipamentos/$id'
      fullPath: '/app/equipamentos/$id'
      preLoaderRoute: typeof AppEquipamentosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppComercialRoute: typeof AppComercialRoute
  AppPontoRoute: typeof AppPontoRoute
  AppWebmailRoute: typeof AppWebmailRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEquipamentosIdRoute: typeof AppEquipamentosIdRoute
  AppProjetosIdRoute: typeof AppProjetosIdRoute
  AppEquipamentosIndexRoute: typeof AppEquipamentosIndexRoute
  AppProjetosIndexRoute: typeof AppProjetosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppComercialRoute: AppComercialRoute,
  AppPontoRoute: AppPontoRoute,
  AppWebmailRoute: AppWebmailRoute,
  AppIndexRoute: AppIndexRoute,
  AppEquipamentosIdRoute: AppEquipamentosIdRoute,
  AppProjetosIdRoute: AppProjetosIdRoute,
  AppEquipamentosIndexRoute: AppEquipamentosIndexRoute,
  AppProjetosIndexRoute: AppProjetosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
