/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CandidatoRouteImport } from './routes/candidato'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PontoRouteImport } from './routes/ponto'
import { Route as TrabalheConoscoRouteImport } from './routes/trabalhe-conosco'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppComercialRouteImport } from './routes/app.comercial'
import { Route as AppEpisRouteImport } from './routes/app.epis'
import { Route as AppPontoRouteImport } from './routes/app.ponto'
import { Route as AppPrevisaoRouteImport } from './routes/app.previsao'
import { Route as AppWebmailRouteImport } from './routes/app.webmail'
import { Route as VagasSlugRouteImport } from './routes/vagas.$slug'
import { Route as AppClientesIndexRouteImport } from './routes/app.clientes.index'
import { Route as AppClientesIdRouteImport } from './routes/app.clientes.$id'
import { Route as AppEpisIndexRouteImport } from './routes/app.epis.index'
import { Route as AppEpisCatalogoRouteImport } from './routes/app.epis.catalogo'
import { Route as AppEpisComprasRouteImport } from './routes/app.epis.compras'
import { Route as AppEpisEntregasRouteImport } from './routes/app.epis.entregas'
import { Route as AppEpisFuncionariosRouteImport } from './routes/app.epis.funcionarios'
import { Route as AppFinanceiroIndexRouteImport } from './routes/app.financeiro.index'
import { Route as AppFinanceiroPagarRouteImport } from './routes/app.financeiro.pagar'
import { Route as AppFinanceiroReceberRouteImport } from './routes/app.financeiro.receber'
import { Route as AppIntegracoesIndexRouteImport } from './routes/app.integracoes.index'
import { Route as AppIntegracoesContaazulRouteImport } from './routes/app.integracoes.contaazul'
import { Route as AppPontoIndexRouteImport } from './routes/app.ponto.index'
import { Route as AppPontoBaterRouteImport } from './routes/app.ponto.bater'
import { Route as AppPontoDashboardRouteImport } from './routes/app.ponto.dashboard'
import { Route as AppPontoIntegracaoRouteImport } from './routes/app.ponto.integracao'
import { Route as AppProjetosIndexRouteImport } from './routes/app.projetos.index'
import { Route as AppProjetosIdRouteImport } from './routes/app.projetos.$id'
import { Route as AppRhIndexRouteImport } from './routes/app.rh.index'
import { Route as AppRhAdmissoesRouteImport } from './routes/app.rh.admissoes'
import { Route as AppRhCandidatosRouteImport } from './routes/app.rh.candidatos'
import { Route as AppRhCargosRouteImport } from './routes/app.rh.cargos'
import { Route as AppRhColaboradoresRouteImport } from './routes/app.rh.colaboradores'
import { Route as AppRhConfiguracoesRouteImport } from './routes/app.rh.configuracoes'
import { Route as AppRhDocumentosRouteImport } from './routes/app.rh.documentos'
import { Route as AppRhSelecaoRouteImport } from './routes/app.rh.selecao'
import { Route as AppRhVagasRouteImport } from './routes/app.rh.vagas'
import { Route as AppRhIntegracoesSecullumRouteImport } from './routes/app.rh.integracoes.secullum'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoRoute = CandidatoRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoRoute = PontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalheConoscoRoute = TrabalheConoscoRouteImport.update({
  id: '/trabalhe-conosco',
  path: '/trabalhe-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppComercialRoute = AppComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AppRoute,
} as any)
const AppEpisRoute = AppEpisRouteImport.update({
  id: '/epis',
  path: '/epis',
  getParentRoute: () => AppRoute,
} as any)
const AppPontoRoute = AppPontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => AppRoute,
} as any)
const AppPrevisaoRoute = AppPrevisaoRouteImport.update({
  id: '/previsao',
  path: '/previsao',
  getParentRoute: () => AppRoute,
} as any)
const AppWebmailRoute = AppWebmailRouteImport.update({
  id: '/webmail',
  path: '/webmail',
  getParentRoute: () => AppRoute,
} as any)
const VagasSlugRoute = VagasSlugRouteImport.update({
  id: '/vagas/$slug',
  path: '/vagas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEpisIndexRoute = AppEpisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEpisRoute,
} as any)
const AppEpisCatalogoRoute = AppEpisCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppEpisRoute,
} as any)
const AppEpisComprasRoute = AppEpisComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppEpisRoute,
} as any)
const AppEpisEntregasRoute = AppEpisEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AppEpisRoute,
} as any)
const AppEpisFuncionariosRoute = AppEpisFuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => AppEpisRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroPagarRoute = AppFinanceiroPagarRouteImport.update({
  id: '/financeiro/pagar',
  path: '/financeiro/pagar',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroReceberRoute = AppFinanceiroReceberRouteImport.update({
  id: '/financeiro/receber',
  path: '/financeiro/receber',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesIndexRoute = AppIntegracoesIndexRouteImport.update({
  id: '/integracoes/',
  path: '/integracoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesContaazulRoute = AppIntegracoesContaazulRouteImport.update({
  id: '/integracoes/contaazul',
  path: '/integracoes/contaazul',
  getParentRoute: () => AppRoute,
} as any)
const AppPontoIndexRoute = AppPontoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPontoRoute,
} as any)
const AppPontoBaterRoute = AppPontoBaterRouteImport.update({
  id: '/bater',
  path: '/bater',
  getParentRoute: () => AppPontoRoute,
} as any)
const AppPontoDashboardRoute = AppPontoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppPontoRoute,
} as any)
const AppPontoIntegracaoRoute = AppPontoIntegracaoRouteImport.update({
  id: '/integracao',
  path: '/integracao',
  getParentRoute: () => AppPontoRoute,
} as any)
const AppProjetosIndexRoute = AppProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosIdRoute = AppProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRhIndexRoute = AppRhIndexRouteImport.update({
  id: '/rh/',
  path: '/rh/',
  getParentRoute: () => AppRoute,
} as any)
const AppRhAdmissoesRoute = AppRhAdmissoesRouteImport.update({
  id: '/rh/admissoes',
  path: '/rh/admissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppRhCandidatosRoute = AppRhCandidatosRouteImport.update({
  id: '/rh/candidatos',
  path: '/rh/candidatos',
  getParentRoute: () => AppRoute,
} as any)
const AppRhCargosRoute = AppRhCargosRouteImport.update({
  id: '/rh/cargos',
  path: '/rh/cargos',
  getParentRoute: () => AppRoute,
} as any)
const AppRhColaboradoresRoute = AppRhColaboradoresRouteImport.update({
  id: '/rh/colaboradores',
  path: '/rh/colaboradores',
  getParentRoute: () => AppRoute,
} as any)
const AppRhConfiguracoesRoute = AppRhConfiguracoesRouteImport.update({
  id: '/rh/configuracoes',
  path: '/rh/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppRhDocumentosRoute = AppRhDocumentosRouteImport.update({
  id: '/rh/documentos',
  path: '/rh/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppRhSelecaoRoute = AppRhSelecaoRouteImport.update({
  id: '/rh/selecao',
  path: '/rh/selecao',
  getParentRoute: () => AppRoute,
} as any)
const AppRhVagasRoute = AppRhVagasRouteImport.update({
  id: '/rh/vagas',
  path: '/rh/vagas',
  getParentRoute: () => AppRoute,
} as any)
const AppRhIntegracoesSecullumRoute =
  AppRhIntegracoesSecullumRouteImport.update({
    id: '/rh/integracoes/secullum',
    path: '/rh/integracoes/secullum',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/candidato': typeof CandidatoRoute
  '/login': typeof LoginRoute
  '/ponto': typeof PontoRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/app/admin': typeof AppAdminRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/epis': typeof AppEpisRouteWithChildren
  '/app/ponto': typeof AppPontoRouteWithChildren
  '/app/previsao': typeof AppPrevisaoRoute
  '/app/webmail': typeof AppWebmailRoute
  '/vagas/$slug': typeof VagasSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/epis/catalogo': typeof AppEpisCatalogoRoute
  '/app/epis/compras': typeof AppEpisComprasRoute
  '/app/epis/entregas': typeof AppEpisEntregasRoute
  '/app/epis/funcionarios': typeof AppEpisFuncionariosRoute
  '/app/financeiro/pagar': typeof AppFinanceiroPagarRoute
  '/app/financeiro/receber': typeof AppFinanceiroReceberRoute
  '/app/integracoes/contaazul': typeof AppIntegracoesContaazulRoute
  '/app/ponto/bater': typeof AppPontoBaterRoute
  '/app/ponto/dashboard': typeof AppPontoDashboardRoute
  '/app/ponto/integracao': typeof AppPontoIntegracaoRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
  '/app/rh/admissoes': typeof AppRhAdmissoesRoute
  '/app/rh/candidatos': typeof AppRhCandidatosRoute
  '/app/rh/cargos': typeof AppRhCargosRoute
  '/app/rh/colaboradores': typeof AppRhColaboradoresRoute
  '/app/rh/configuracoes': typeof AppRhConfiguracoesRoute
  '/app/rh/documentos': typeof AppRhDocumentosRoute
  '/app/rh/selecao': typeof AppRhSelecaoRoute
  '/app/rh/vagas': typeof AppRhVagasRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/epis/': typeof AppEpisIndexRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/app/integracoes/': typeof AppIntegracoesIndexRoute
  '/app/ponto/': typeof AppPontoIndexRoute
  '/app/projetos/': typeof AppProjetosIndexRoute
  '/app/rh/': typeof AppRhIndexRoute
  '/app/rh/integracoes/secullum': typeof AppRhIntegracoesSecullumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidato': typeof CandidatoRoute
  '/login': typeof LoginRoute
  '/ponto': typeof PontoRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/app/admin': typeof AppAdminRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/previsao': typeof AppPrevisaoRoute
  '/app/webmail': typeof AppWebmailRoute
  '/vagas/$slug': typeof VagasSlugRoute
  '/app': typeof AppIndexRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/epis/catalogo': typeof AppEpisCatalogoRoute
  '/app/epis/compras': typeof AppEpisComprasRoute
  '/app/epis/entregas': typeof AppEpisEntregasRoute
  '/app/epis/funcionarios': typeof AppEpisFuncionariosRoute
  '/app/financeiro/pagar': typeof AppFinanceiroPagarRoute
  '/app/financeiro/receber': typeof AppFinanceiroReceberRoute
  '/app/integracoes/contaazul': typeof AppIntegracoesContaazulRoute
  '/app/ponto/bater': typeof AppPontoBaterRoute
  '/app/ponto/dashboard': typeof AppPontoDashboardRoute
  '/app/ponto/integracao': typeof AppPontoIntegracaoRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
  '/app/rh/admissoes': typeof AppRhAdmissoesRoute
  '/app/rh/candidatos': typeof AppRhCandidatosRoute
  '/app/rh/cargos': typeof AppRhCargosRoute
  '/app/rh/colaboradores': typeof AppRhColaboradoresRoute
  '/app/rh/configuracoes': typeof AppRhConfiguracoesRoute
  '/app/rh/documentos': typeof AppRhDocumentosRoute
  '/app/rh/selecao': typeof AppRhSelecaoRoute
  '/app/rh/vagas': typeof AppRhVagasRoute
  '/app/clientes': typeof AppClientesIndexRoute
  '/app/epis': typeof AppEpisIndexRoute
  '/app/financeiro': typeof AppFinanceiroIndexRoute
  '/app/integracoes': typeof AppIntegracoesIndexRoute
  '/app/ponto': typeof AppPontoIndexRoute
  '/app/projetos': typeof AppProjetosIndexRoute
  '/app/rh': typeof AppRhIndexRoute
  '/app/rh/integracoes/secullum': typeof AppRhIntegracoesSecullumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/candidato': typeof CandidatoRoute
  '/login': typeof LoginRoute
  '/ponto': typeof PontoRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/app/admin': typeof AppAdminRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/epis': typeof AppEpisRouteWithChildren
  '/app/ponto': typeof AppPontoRouteWithChildren
  '/app/previsao': typeof AppPrevisaoRoute
  '/app/webmail': typeof AppWebmailRoute
  '/vagas/$slug': typeof VagasSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/$id': typeof AppClientesIdRoute
  '/app/epis/catalogo': typeof AppEpisCatalogoRoute
  '/app/epis/compras': typeof AppEpisComprasRoute
  '/app/epis/entregas': typeof AppEpisEntregasRoute
  '/app/epis/funcionarios': typeof AppEpisFuncionariosRoute
  '/app/financeiro/pagar': typeof AppFinanceiroPagarRoute
  '/app/financeiro/receber': typeof AppFinanceiroReceberRoute
  '/app/integracoes/contaazul': typeof AppIntegracoesContaazulRoute
  '/app/ponto/bater': typeof AppPontoBaterRoute
  '/app/ponto/dashboard': typeof AppPontoDashboardRoute
  '/app/ponto/integracao': typeof AppPontoIntegracaoRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
  '/app/rh/admissoes': typeof AppRhAdmissoesRoute
  '/app/rh/candidatos': typeof AppRhCandidatosRoute
  '/app/rh/cargos': typeof AppRhCargosRoute
  '/app/rh/colaboradores': typeof AppRhColaboradoresRoute
  '/app/rh/configuracoes': typeof AppRhConfiguracoesRoute
  '/app/rh/documentos': typeof AppRhDocumentosRoute
  '/app/rh/selecao': typeof AppRhSelecaoRoute
  '/app/rh/vagas': typeof AppRhVagasRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/epis/': typeof AppEpisIndexRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/app/integracoes/': typeof AppIntegracoesIndexRoute
  '/app/ponto/': typeof AppPontoIndexRoute
  '/app/projetos/': typeof AppProjetosIndexRoute
  '/app/rh/': typeof AppRhIndexRoute
  '/app/rh/integracoes/secullum': typeof AppRhIntegracoesSecullumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/candidato'
    | '/login'
    | '/ponto'
    | '/trabalhe-conosco'
    | '/app/admin'
    | '/app/comercial'
    | '/app/epis'
    | '/app/ponto'
    | '/app/previsao'
    | '/app/webmail'
    | '/vagas/$slug'
    | '/app/'
    | '/app/clientes/$id'
    | '/app/epis/catalogo'
    | '/app/epis/compras'
    | '/app/epis/entregas'
    | '/app/epis/funcionarios'
    | '/app/financeiro/pagar'
    | '/app/financeiro/receber'
    | '/app/integracoes/contaazul'
    | '/app/ponto/bater'
    | '/app/ponto/dashboard'
    | '/app/ponto/integracao'
    | '/app/projetos/$id'
    | '/app/rh/admissoes'
    | '/app/rh/candidatos'
    | '/app/rh/cargos'
    | '/app/rh/colaboradores'
    | '/app/rh/configuracoes'
    | '/app/rh/documentos'
    | '/app/rh/selecao'
    | '/app/rh/vagas'
    | '/app/clientes/'
    | '/app/epis/'
    | '/app/financeiro/'
    | '/app/integracoes/'
    | '/app/ponto/'
    | '/app/projetos/'
    | '/app/rh/'
    | '/app/rh/integracoes/secullum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidato'
    | '/login'
    | '/ponto'
    | '/trabalhe-conosco'
    | '/app/admin'
    | '/app/comercial'
    | '/app/previsao'
    | '/app/webmail'
    | '/vagas/$slug'
    | '/app'
    | '/app/clientes/$id'
    | '/app/epis/catalogo'
    | '/app/epis/compras'
    | '/app/epis/entregas'
    | '/app/epis/funcionarios'
    | '/app/financeiro/pagar'
    | '/app/financeiro/receber'
    | '/app/integracoes/contaazul'
    | '/app/ponto/bater'
    | '/app/ponto/dashboard'
    | '/app/ponto/integracao'
    | '/app/projetos/$id'
    | '/app/rh/admissoes'
    | '/app/rh/candidatos'
    | '/app/rh/cargos'
    | '/app/rh/colaboradores'
    | '/app/rh/configuracoes'
    | '/app/rh/documentos'
    | '/app/rh/selecao'
    | '/app/rh/vagas'
    | '/app/clientes'
    | '/app/epis'
    | '/app/financeiro'
    | '/app/integracoes'
    | '/app/ponto'
    | '/app/projetos'
    | '/app/rh'
    | '/app/rh/integracoes/secullum'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/candidato'
    | '/login'
    | '/ponto'
    | '/trabalhe-conosco'
    | '/app/admin'
    | '/app/comercial'
    | '/app/epis'
    | '/app/ponto'
    | '/app/previsao'
    | '/app/webmail'
    | '/vagas/$slug'
    | '/app/'
    | '/app/clientes/$id'
    | '/app/epis/catalogo'
    | '/app/epis/compras'
    | '/app/epis/entregas'
    | '/app/epis/funcionarios'
    | '/app/financeiro/pagar'
    | '/app/financeiro/receber'
    | '/app/integracoes/contaazul'
    | '/app/ponto/bater'
    | '/app/ponto/dashboard'
    | '/app/ponto/integracao'
    | '/app/projetos/$id'
    | '/app/rh/admissoes'
    | '/app/rh/candidatos'
    | '/app/rh/cargos'
    | '/app/rh/colaboradores'
    | '/app/rh/configuracoes'
    | '/app/rh/documentos'
    | '/app/rh/selecao'
    | '/app/rh/vagas'
    | '/app/clientes/'
    | '/app/epis/'
    | '/app/financeiro/'
    | '/app/integracoes/'
    | '/app/ponto/'
    | '/app/projetos/'
    | '/app/rh/'
    | '/app/rh/integracoes/secullum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CandidatoRoute: typeof CandidatoRoute
  LoginRoute: typeof LoginRoute
  PontoRoute: typeof PontoRoute
  TrabalheConoscoRoute: typeof TrabalheConoscoRoute
  VagasSlugRoute: typeof VagasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato': {
      id: '/candidato'
      path: '/candidato'
      fullPath: '/candidato'
      preLoaderRoute: typeof CandidatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto': {
      id: '/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof PontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhe-conosco': {
      id: '/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/trabalhe-conosco'
      preLoaderRoute: typeof TrabalheConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comercial': {
      id: '/app/comercial'
      path: '/comercial'
      fullPath: '/app/comercial'
      preLoaderRoute: typeof AppComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/epis': {
      id: '/app/epis'
      path: '/epis'
      fullPath: '/app/epis'
      preLoaderRoute: typeof AppEpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ponto': {
      id: '/app/ponto'
      path: '/ponto'
      fullPath: '/app/ponto'
      preLoaderRoute: typeof AppPontoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/previsao': {
      id: '/app/previsao'
      path: '/previsao'
      fullPath: '/app/previsao'
      preLoaderRoute: typeof AppPrevisaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webmail': {
      id: '/app/webmail'
      path: '/webmail'
      fullPath: '/app/webmail'
      preLoaderRoute: typeof AppWebmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/vagas/$slug': {
      id: '/vagas/$slug'
      path: '/vagas/$slug'
      fullPath: '/vagas/$slug'
      preLoaderRoute: typeof VagasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clientes/': {
      id: '/app/clientes/'
      path: '/clientes'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/$id': {
      id: '/app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/app/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/epis/': {
      id: '/app/epis/'
      path: '/'
      fullPath: '/app/epis/'
      preLoaderRoute: typeof AppEpisIndexRouteImport
      parentRoute: typeof AppEpisRoute
    }
    '/app/epis/catalogo': {
      id: '/app/epis/catalogo'
      path: '/catalogo'
      fullPath: '/app/epis/catalogo'
      preLoaderRoute: typeof AppEpisCatalogoRouteImport
      parentRoute: typeof AppEpisRoute
    }
    '/app/epis/compras': {
      id: '/app/epis/compras'
      path: '/compras'
      fullPath: '/app/epis/compras'
      preLoaderRoute: typeof AppEpisComprasRouteImport
      parentRoute: typeof AppEpisRoute
    }
    '/app/epis/entregas': {
      id: '/app/epis/entregas'
      path: '/entregas'
      fullPath: '/app/epis/entregas'
      preLoaderRoute: typeof AppEpisEntregasRouteImport
      parentRoute: typeof AppEpisRoute
    }
    '/app/epis/funcionarios': {
      id: '/app/epis/funcionarios'
      path: '/funcionarios'
      fullPath: '/app/epis/funcionarios'
      preLoaderRoute: typeof AppEpisFuncionariosRouteImport
      parentRoute: typeof AppEpisRoute
    }
    '/app/financeiro/': {
      id: '/app/financeiro/'
      path: '/financeiro'
      fullPath: '/app/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro/pagar': {
      id: '/app/financeiro/pagar'
      path: '/financeiro/pagar'
      fullPath: '/app/financeiro/pagar'
      preLoaderRoute: typeof AppFinanceiroPagarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro/receber': {
      id: '/app/financeiro/receber'
      path: '/financeiro/receber'
      fullPath: '/app/financeiro/receber'
      preLoaderRoute: typeof AppFinanceiroReceberRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integracoes/': {
      id: '/app/integracoes/'
      path: '/integracoes'
      fullPath: '/app/integracoes/'
      preLoaderRoute: typeof AppIntegracoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integracoes/contaazul': {
      id: '/app/integracoes/contaazul'
      path: '/integracoes/contaazul'
      fullPath: '/app/integracoes/contaazul'
      preLoaderRoute: typeof AppIntegracoesContaazulRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ponto/': {
      id: '/app/ponto/'
      path: '/'
      fullPath: '/app/ponto/'
      preLoaderRoute: typeof AppPontoIndexRouteImport
      parentRoute: typeof AppPontoRoute
    }
    '/app/ponto/bater': {
      id: '/app/ponto/bater'
      path: '/bater'
      fullPath: '/app/ponto/bater'
      preLoaderRoute: typeof AppPontoBaterRouteImport
      parentRoute: typeof AppPontoRoute
    }
    '/app/ponto/dashboard': {
      id: '/app/ponto/dashboard'
      path: '/dashboard'
      fullPath: '/app/ponto/dashboard'
      preLoaderRoute: typeof AppPontoDashboardRouteImport
      parentRoute: typeof AppPontoRoute
    }
    '/app/ponto/integracao': {
      id: '/app/ponto/integracao'
      path: '/integracao'
      fullPath: '/app/ponto/integracao'
      preLoaderRoute: typeof AppPontoIntegracaoRouteImport
      parentRoute: typeof AppPontoRoute
    }
    '/app/projetos/': {
      id: '/app/projetos/'
      path: '/projetos'
      fullPath: '/app/projetos/'
      preLoaderRoute: typeof AppProjetosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos/$id': {
      id: '/app/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/app/projetos/$id'
      preLoaderRoute: typeof AppProjetosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh/': {
      id: '/app/rh/'
      path: '/rh'
      fullPath: '/app/rh/'
      preLoaderRoute: typeof AppRhIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh/admissoes': {
      id: '/app/rh/admissoes'
      path: '/rh/admissoes'
      fullPath: '/app/rh/admissoes'
      preLoaderRoute: typeof AppRhAdmissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh/candidatos': {
      id: '/app/rh/candidatos'
      path: '/rh/candidatos'
      fullPath: '/app/rh/candidatos'
      preLoaderRoute: typeof AppRhCandidatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh/cargos': {
      id: '/app/rh/cargos'
      path: '/rh/cargos'
      fullPath: '/app/rh/cargos'
      preLoaderRoute: typeof AppRhCargosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh/colaboradores': {
      id: '/app/rh/colaboradores'
      path: '/rh/colaboradores'
      fullPath: '/app/rh/colaboradores'
      preLoaderRoute: typeof AppRhColaboradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh/configuracoes': {
      id: '/app/rh/configuracoes'
      path: '/rh/configuracoes'
      fullPath: '/app/rh/configuracoes'
      preLoaderRoute: typeof AppRhConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh/documentos': {
      id: '/app/rh/documentos'
      path: '/rh/documentos'
      fullPath: '/app/rh/documentos'
      preLoaderRoute: typeof AppRhDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh/selecao': {
      id: '/app/rh/selecao'
      path: '/rh/selecao'
      fullPath: '/app/rh/selecao'
      preLoaderRoute: typeof AppRhSelecaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh/vagas': {
      id: '/app/rh/vagas'
      path: '/rh/vagas'
      fullPath: '/app/rh/vagas'
      preLoaderRoute: typeof AppRhVagasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rh/integracoes/secullum': {
      id: '/app/rh/integracoes/secullum'
      path: '/rh/integracoes/secullum'
      fullPath: '/app/rh/integracoes/secullum'
      preLoaderRoute: typeof AppRhIntegracoesSecullumRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppEpisRouteChildren {
  AppEpisCatalogoRoute: typeof AppEpisCatalogoRoute
  AppEpisComprasRoute: typeof AppEpisComprasRoute
  AppEpisEntregasRoute: typeof AppEpisEntregasRoute
  AppEpisFuncionariosRoute: typeof AppEpisFuncionariosRoute
  AppEpisIndexRoute: typeof AppEpisIndexRoute
}

const AppEpisRouteChildren: AppEpisRouteChildren = {
  AppEpisCatalogoRoute: AppEpisCatalogoRoute,
  AppEpisComprasRoute: AppEpisComprasRoute,
  AppEpisEntregasRoute: AppEpisEntregasRoute,
  AppEpisFuncionariosRoute: AppEpisFuncionariosRoute,
  AppEpisIndexRoute: AppEpisIndexRoute,
}

const AppEpisRouteWithChildren =
  AppEpisRoute._addFileChildren(AppEpisRouteChildren)

interface AppPontoRouteChildren {
  AppPontoBaterRoute: typeof AppPontoBaterRoute
  AppPontoDashboardRoute: typeof AppPontoDashboardRoute
  AppPontoIntegracaoRoute: typeof AppPontoIntegracaoRoute
  AppPontoIndexRoute: typeof AppPontoIndexRoute
}

const AppPontoRouteChildren: AppPontoRouteChildren = {
  AppPontoBaterRoute: AppPontoBaterRoute,
  AppPontoDashboardRoute: AppPontoDashboardRoute,
  AppPontoIntegracaoRoute: AppPontoIntegracaoRoute,
  AppPontoIndexRoute: AppPontoIndexRoute,
}

const AppPontoRouteWithChildren = AppPontoRoute._addFileChildren(
  AppPontoRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppComercialRoute: typeof AppComercialRoute
  AppEpisRoute: typeof AppEpisRouteWithChildren
  AppPontoRoute: typeof AppPontoRouteWithChildren
  AppPrevisaoRoute: typeof AppPrevisaoRoute
  AppWebmailRoute: typeof AppWebmailRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppFinanceiroPagarRoute: typeof AppFinanceiroPagarRoute
  AppFinanceiroReceberRoute: typeof AppFinanceiroReceberRoute
  AppIntegracoesContaazulRoute: typeof AppIntegracoesContaazulRoute
  AppProjetosIdRoute: typeof AppProjetosIdRoute
  AppRhAdmissoesRoute: typeof AppRhAdmissoesRoute
  AppRhCandidatosRoute: typeof AppRhCandidatosRoute
  AppRhCargosRoute: typeof AppRhCargosRoute
  AppRhColaboradoresRoute: typeof AppRhColaboradoresRoute
  AppRhConfiguracoesRoute: typeof AppRhConfiguracoesRoute
  AppRhDocumentosRoute: typeof AppRhDocumentosRoute
  AppRhSelecaoRoute: typeof AppRhSelecaoRoute
  AppRhVagasRoute: typeof AppRhVagasRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
  AppIntegracoesIndexRoute: typeof AppIntegracoesIndexRoute
  AppProjetosIndexRoute: typeof AppProjetosIndexRoute
  AppRhIndexRoute: typeof AppRhIndexRoute
  AppRhIntegracoesSecullumRoute: typeof AppRhIntegracoesSecullumRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppComercialRoute: AppComercialRoute,
  AppEpisRoute: AppEpisRouteWithChildren,
  AppPontoRoute: AppPontoRouteWithChildren,
  AppPrevisaoRoute: AppPrevisaoRoute,
  AppWebmailRoute: AppWebmailRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppFinanceiroPagarRoute: AppFinanceiroPagarRoute,
  AppFinanceiroReceberRoute: AppFinanceiroReceberRoute,
  AppIntegracoesContaazulRoute: AppIntegracoesContaazulRoute,
  AppProjetosIdRoute: AppProjetosIdRoute,
  AppRhAdmissoesRoute: AppRhAdmissoesRoute,
  AppRhCandidatosRoute: AppRhCandidatosRoute,
  AppRhCargosRoute: AppRhCargosRoute,
  AppRhColaboradoresRoute: AppRhColaboradoresRoute,
  AppRhConfiguracoesRoute: AppRhConfiguracoesRoute,
  AppRhDocumentosRoute: AppRhDocumentosRoute,
  AppRhSelecaoRoute: AppRhSelecaoRoute,
  AppRhVagasRoute: AppRhVagasRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
  AppIntegracoesIndexRoute: AppIntegracoesIndexRoute,
  AppProjetosIndexRoute: AppProjetosIndexRoute,
  AppRhIndexRoute: AppRhIndexRoute,
  AppRhIntegracoesSecullumRoute: AppRhIntegracoesSecullumRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CandidatoRoute: CandidatoRoute,
  LoginRoute: LoginRoute,
  PontoRoute: PontoRoute,
  TrabalheConoscoRoute: TrabalheConoscoRoute,
  VagasSlugRoute: VagasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
