/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWebmailRouteImport } from './routes/app.webmail'
import { Route as AppProjetosRouteImport } from './routes/app.projetos'
import { Route as AppEquipamentosRouteImport } from './routes/app.equipamentos'
import { Route as AppComercialRouteImport } from './routes/app.comercial'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppProjetosIdRouteImport } from './routes/app.projetos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebmailRoute = AppWebmailRouteImport.update({
  id: '/webmail',
  path: '/webmail',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipamentosRoute = AppEquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppComercialRoute = AppComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosIdRoute = AppProjetosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjetosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/projetos': typeof AppProjetosRouteWithChildren
  '/app/webmail': typeof AppWebmailRoute
  '/app/': typeof AppIndexRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/projetos': typeof AppProjetosRouteWithChildren
  '/app/webmail': typeof AppWebmailRoute
  '/app': typeof AppIndexRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/comercial': typeof AppComercialRoute
  '/app/equipamentos': typeof AppEquipamentosRoute
  '/app/projetos': typeof AppProjetosRouteWithChildren
  '/app/webmail': typeof AppWebmailRoute
  '/app/': typeof AppIndexRoute
  '/app/projetos/$id': typeof AppProjetosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/comercial'
    | '/app/equipamentos'
    | '/app/projetos'
    | '/app/webmail'
    | '/app/'
    | '/app/projetos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/admin'
    | '/app/comercial'
    | '/app/equipamentos'
    | '/app/projetos'
    | '/app/webmail'
    | '/app'
    | '/app/projetos/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/comercial'
    | '/app/equipamentos'
    | '/app/projetos'
    | '/app/webmail'
    | '/app/'
    | '/app/projetos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/webmail': {
      id: '/app/webmail'
      path: '/webmail'
      fullPath: '/app/webmail'
      preLoaderRoute: typeof AppWebmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipamentos': {
      id: '/app/equipamentos'
      path: '/equipamentos'
      fullPath: '/app/equipamentos'
      preLoaderRoute: typeof AppEquipamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comercial': {
      id: '/app/comercial'
      path: '/comercial'
      fullPath: '/app/comercial'
      preLoaderRoute: typeof AppComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos/$id': {
      id: '/app/projetos/$id'
      path: '/$id'
      fullPath: '/app/projetos/$id'
      preLoaderRoute: typeof AppProjetosIdRouteImport
      parentRoute: typeof AppProjetosRoute
    }
  }
}

interface AppProjetosRouteChildren {
  AppProjetosIdRoute: typeof AppProjetosIdRoute
}

const AppProjetosRouteChildren: AppProjetosRouteChildren = {
  AppProjetosIdRoute: AppProjetosIdRoute,
}

const AppProjetosRouteWithChildren = AppProjetosRoute._addFileChildren(
  AppProjetosRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppComercialRoute: typeof AppComercialRoute
  AppEquipamentosRoute: typeof AppEquipamentosRoute
  AppProjetosRoute: typeof AppProjetosRouteWithChildren
  AppWebmailRoute: typeof AppWebmailRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppComercialRoute: AppComercialRoute,
  AppEquipamentosRoute: AppEquipamentosRoute,
  AppProjetosRoute: AppProjetosRouteWithChildren,
  AppWebmailRoute: AppWebmailRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
